package common

type ERROR_CODES string

const (
	INTERNAL_SERVER_ERROR  ERROR_CODES = "INTERNAL_SERVER_ERROR"
	URI_NOT_FOUND          ERROR_CODES = "URI_NOT_FOUND"
	INVALID_PARAMETER      ERROR_CODES = "INVALID_PARAMETER"
	FIELD_REQUIRED         ERROR_CODES = "FIELD_REQUIRED"
	VALUE_INVALID          ERROR_CODES = "VALUE_INVALID"
	TIMEOUT_ERROR          ERROR_CODES = "TIMEOUT_ERROR"
	UNAUTHORIZED           ERROR_CODES = "UNAUTHORIZED"
	OBJECT_NOT_FOUND       ERROR_CODES = "OBJECT_NOT_FOUND"
	SECOND_FACTOR_REQUIRED ERROR_CODES = "SECOND_FACTOR_REQUIRED"
)
